### PR TITLE
Fix clippy warnings

### LINKED ISSUE #58: Fix clippy lints

### PR DESCRIPTION
**Pull request by okrplay**
Fixes #58. I changed the code where the warnings pointed to, unless it didn't make sense to, in that case I added an allow-attribute.

### CODE REVIEW

File: src/serializer/elements.rs [hunk 1]
```diff
@@ -528,6 +540,8 @@ impl<'a> EbmlSize for Cluster<'a> {
     }
 }
 
+// Clippy thinks this function is too complicated, but it doesn't really make sense to split it up
+#[allow(clippy::cognitive_complexity)]
```
Comment (lu-zero) [inline src/serializer/elements.rs]: we might disable the cognitive complexity lint at crate-level later maybe.

Comment (okrplay) [reply src/serializer/elements.rs]: Yeah, that would make sense if more functions like the gen-functions are added.
